---
- name: IOS automated CLI example
  hosts: iosrouters
  gather_facts: no
  collections:
    - cisco.ios

  tasks:

  - name: set ACL via CLI
    ios_config:
      lines:
        - 10 permit ip host 1.1.1.1 any log
        - 20 permit ip host 2.2.2.2 any log
        - 30 permit ip host 3.3.3.3 any log
        - 40 permit ip host 4.4.4.4 any log
        - 50 permit ip host 5.5.5.5 any log
      parents: ['ip access-list extended pod_{{pod}}_acl']

  - name: set ntp server 10.1.{{pod}}.{{item}} via CLI loop
    ios_config:
      lines:
        - ntp server 10.1.{{pod}}.{{item}}
    loop:
        - 11
        - 12
        - 13

