---
- name: Jinja2 template example
  hosts: iosrouters
  gather_facts: false

  tasks:
  
  - name: configure hostname with Jinja2 template
    cli_config:
      config: "{{ lookup('template', 'template.j2') }}"
