---
- name: Enable NETCONF on IOS routers
  hosts: iosrouters
  gather_facts: no
  roles:
    - netconf_router

- name: Enable NX-API on NX-OS switches
  hosts: nxosswitches
  gather_facts: no
  roles:
    - nxapi_switch